ru:
  global:
    title: 'Дари Добро! - фестиваль благотворительности'
  concert:
    title: 'Концерты'
    partners: 'Партнёры концерта'
  header:
    volunteers: 'волонтёрам'
    soondate: 'Концерт состоится'
    festivalname: 'фестиваль Благотворительности'
    helptitle: 'Поддержать проект'
    help: 'Помощь'
  nav:
    home: 'Главная'
    concert: 'Концерт'
    news: 'Новости'
    members: 'Участники'
    help: 'Поддержать проект'
    gallery: 'Галерея'
    contact: 'Связь с нами'
  footer:
    copyrightfirst: 'Благотворительный фонд '
    copyrightname: '«Пчёлка»'
    designed: 'Сайт разработан в '
  home:
    pastconcerts: 'Концерты прошлых лет'
    partnersofconcert: 'Партнёры концерта '
    aboutconcert: 'О концерте'
    detail: 'Подробнее'
  browserdetect:
    text: 'Вы пользуетесь устаревшей версией браузера Internet Explorer. Данная версия браузера не поддерживает многие современные технологии, из-за чего многие страницы отображаются некорректно, а главное — на сайтах могут работать не все функции. В связи с этим на Ваш суд представляются более современные браузеры. Все они бесплатны, легко устанавливаются и просты в использовании. При переходе на любой нижеуказанный браузер все ваши закладки и пароли будут перенесены из текущего браузера, вы ничего не потеряете.'
  help:
    title: 'Поддержать проект'
    reqs: 'реквизиты'
    callback: 'Обратная связь'
  news:
    rubric: 'Рубрики'
    tags: 'Тэги'
    author: 'Автор'
    news: 'Новости'
    detail: 'Подробнее'
  members:
    title: 'Участники'
    leading: 'Ведущие концерта'
    guest: 'Гости концерта'
    children: 'Для вас выступали'
  gallery:
    title: 'Галерея'
    fotoalbom: 'Фотоальбомы'
    video: 'Видео'
  contact:
    contacts: 'Контакты'
    goback: 'Приходите'
    call: 'Звоните'
    send: 'отправляйте'
    write: 'Пишите'
    ourteam: 'Наша команда'
    callback: 'Обратная связь'
  volback:
    title_vol: "Форма волонтёра"
    title_back: "Обратная связь"
    fio: "ФИО"
    age: "Возраст"
    tel: "Телефон"
    email: "Email"
    text: "Ваш текст сообщения"
    send: "Отправить"